RegisterNetEvent("kaloudas_presence:updatePresence")
AddEventHandler("kaloudas_presence:updatePresence", function(playerCount, maxPlayers)
    SetDiscordAppId(Config.discordAppId)
    SetRichPresence("Players: " .. playerCount .. "/" .. maxPlayers)
    SetDiscordRichPresenceAsset(Config.logoName)
    SetDiscordRichPresenceAssetText(Config.serverName)
    SetDiscordRichPresenceAssetSmall(Config.logoName)
    SetDiscordRichPresenceAssetSmallText("YOUR_SERVER_NAME")
end)
